### ISSUE TITLE
Mapping the Enum type

### ISSUE THREAD

**Issue by Midnighter** [justanr/marshmallow-annotations#24]
Would you see a mapping for the Enum type to a marshmallow field as part of this package or rather something custom that could become a recipe or so?

**Comment by justanr** [comment]
I actually have a marshmallow extension package for handling enums. I purposefully didn't add a dependency on it, but if there's desire it'd be a pretty easy add.

**Comment by Midnighter** [comment]
Seems marshmallow recommends using the `OneOf` validator. Does your extension do that, too? Either way I have a project with a number of enum types and would really appreciate being able to (de-)serialize them.

**Comment by justanr** [comment]
https://github.com/justanr/marshmallow_enu

It doesn't use OneOf but instead it's a custom field type that can handle both string representation and *some* underlying object type (essentially if you're using raw ints or strings under the hood you'll be covered, more complicated representations agent covered and not really supported out of a desire for simplicity)

**Comment by Midnighter** [comment]
I went with a custom field in the end since what I really needed was a `typing.List[Enum]`. Thank you for pointing me to this extension, though.
